theme: jekyll-theme-minimal
title: Binary probit regression with I-priors
description: |
  Department of Statistics PhD Presentation Event. 
  London School of Economics and Political Science, 8-9 May 2017.
