---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", size = "small",
                      prompt = TRUE)
options(prompt = "R> ")

# Load external .R file
knitr::read_chunk("01-prelim.R")
knitr::read_chunk("04-variational-example.R")
knitr::read_chunk("07-cardiac.R")
knitr::read_chunk("08-smoking.R")
```

## Abstract

An extension of the I-prior methodology to binary response data is explored. Starting from a latent variable approach, it is assumed that  there exists continuous, auxiliary random variables which decide the outcome of the binary responses. Modelling these latent variables using an ordinary linear model with normally distributed errors leads to the well-known generalised linear model with a probit link. Instead, a more general regression approach is considered in which an I-prior on the regression function, which lies in some reproducing kernel Hilbert space, is assumed. An I-prior distribution is Gaussian with mean chosen a priori, and covariance equal to the Fisher information for the regression function. By doing so, the benefits of the original I-prior methodology is brought over to the binary case - one of which is providing a unified model fitting methodology that includes additive models, multilevel models and models with one or more functional covariates. The challenge is in the estimation, and a variational approximation is employed to overcome the intractable likelihood. Several real-world examples are presented from analyses conducted in `R`.

*Keywords*: binary, probit, regression, kernel, RKHS, Gaussian, process, multilevel, longitudinal, functional, prior, variational, Bayes, EM

## Links

- Presentation slides - PDF *[link to appear]*
- Source code - [GitHub](https://github.com/haziqjamil/phd-presentation-3)
- R/iprior package - [CRAN](https://cran.r-project.org/package=iprior), [GitHub](https://github.com/haziqjamil/iprior)
- R/iprobit package - [GitHub](https://github.com/haziqjamil/iprobit)

## Supplementary material

### Variational inference for Gaussian mean and precision

### Cardiac arrhythmia data set results

### Meta-analysis of smoking cessation results

Copyright (C) 2017 [Haziq Jamil](http://haziqj.ml). All rights reserved.
